[package]
name = "endecode"
version = "0.1.0"
edition = "2021"

[features]
derive = ["endecode-derive"]

[dependencies]
paste = "1.0.14"
endecode-derive = { path = "../endecode-derive", optional = true }

[dev-dependencies]
rand = "0.8.5"
